# Generated by Django 5.2.17 on 2026-09-30 21:24

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='company/')),
                ('default_gold_rate', models.DecimalField(decimal_places=2, default=Decimal('15000.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('default_fx_rate', models.DecimalField(decimal_places=4, default=Decimal('91.0000'), max_digits=10)),
                ('invoice_footer_text', models.TextField(blank=True)),
                ('payment_direction', models.CharField(choices=[('paid_out', 'Paid out'), ('received', 'Received')], default='paid_out', max_length=8)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('gst_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='settings_singleton'), models.CheckConstraint(condition=models.Q(('gst_rate_percent__gte', 0), ('gst_rate_percent__lte', 100)), name='settings_gst_range'), models.CheckConstraint(condition=models.Q(('default_gold_rate__gte', 0)), name='settings_default_gold_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('default_fx_rate__gte', 0)), name='settings_default_fx_rate_nonnegative')],
            },
        ),
    ]
