# Generated by Django 5.2.17 on 2026-10-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='preview_cache',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
