# Generated by Django 5.2.17 on 2026-09-30 21:34

import accounts.models
import django.db.models.functions.text
from django.db import migrations, models


def prepare_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    seen = set()
    users = list(User.objects.all())
    for user in users:
        key = user.email.strip().lower()
        if not key or key in seen:
            raise RuntimeError('Each user needs a distinct email address. Correct empty or duplicate emails before migrating.')
        seen.add(key)
    for user in users:
        user.email = user.email.strip().lower()
        if user.is_superuser:
            user.role = 'Owner'
        user.save(update_fields=['email', 'role'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ebay_accounts',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='accounts.ebayaccount'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Accounts', 'Accounts'), ('Staff', 'Staff')], default='Staff', max_length=10),
        ),
        migrations.RunPython(prepare_users, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_case_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['Owner', 'Accounts', 'Staff'])), name='user_role_valid'),
        ),
    ]
