# Generated by Django 5.2.17 on 2026-09-30 21:24

import django.db.models.deletion
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(editable=False, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^INV-[0-9]{4}-[0-9]{5,}$', 'Use an invoice number in INV-YYYY-00001 format.')])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Superseded', 'Superseded')], default='Issued', max_length=12)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
