# Generated by Django 5.2.17 on 2026-09-30 21:24

import core.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('serial_no', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('sales_no', models.IntegerField()),
                ('challan_no', models.CharField(blank=True, max_length=100)),
                ('mfg_order_no', models.CharField(blank=True, max_length=100)),
                ('order_date', models.DateField()),
                ('ship_by_date', models.DateField(blank=True, null=True)),
                ('buyer_username', models.CharField(max_length=255)),
                ('item_title', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, upload_to='orders/')),
                ('igi_cert_no', models.CharField(blank=True, max_length=100)),
                ('tracking_no', models.CharField(blank=True, max_length=255)),
                ('fulfilment_status', models.CharField(choices=[('New', 'New'), ('In production', 'In production'), ('Ready', 'Ready'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='New', max_length=20)),
                ('usd_sold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fx_rate', models.DecimalField(decimal_places=4, default=core.models.default_fx_rate, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('inr_sold', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ship_charges', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('platform_fees_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('purity', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0001')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('gross_wt', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('dia_ct', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('other_wt', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gold_rate', models.DecimalField(decimal_places=2, default=core.models.default_gold_rate, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('lab_rate', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('diamond_value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_wt', models.DecimalField(decimal_places=4, editable=False, max_digits=12)),
                ('pure_995', models.DecimalField(decimal_places=6, editable=False, max_digits=15)),
                ('gold_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('labour_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_bill', models.DecimalField(decimal_places=2, editable=False, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_earnings', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.ebayaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('account', 'sales_no'), name='order_account_sales_unique'), models.CheckConstraint(condition=models.Q(('net_wt__gt', 0)), name='order_net_wt_positive'), models.CheckConstraint(condition=models.Q(('gross_wt__gt', 0)), name='order_gross_wt_positive'), models.CheckConstraint(condition=models.Q(('purity__gte', Decimal('0.0001')), ('purity__lte', 1)), name='order_purity_range'), models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_quantity_positive'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='order_version_positive'), models.CheckConstraint(condition=models.Q(('ship_by_date__isnull', True), ('ship_by_date__gte', models.F('order_date')), _connector='OR'), name='order_ship_date_valid'), models.CheckConstraint(condition=models.Q(models.Q(('fulfilment_status', 'Shipped'), _negated=True), models.Q(('tracking_no', ''), _negated=True), _connector='OR'), name='order_shipped_tracking'), models.CheckConstraint(condition=models.Q(('usd_sold__gte', 0)), name='order_usd_sold_nonnegative'), models.CheckConstraint(condition=models.Q(('fx_rate__gte', 0)), name='order_fx_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('inr_sold__gte', 0)), name='order_inr_sold_nonnegative'), models.CheckConstraint(condition=models.Q(('ship_charges__gte', 0)), name='order_ship_charges_nonnegative'), models.CheckConstraint(condition=models.Q(('platform_fees_inr__gte', 0)), name='order_platform_fees_inr_nonnegative'), models.CheckConstraint(condition=models.Q(('gold_rate__gte', 0)), name='order_gold_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('lab_rate__gte', 0)), name='order_lab_rate_nonnegative'), models.CheckConstraint(condition=models.Q(('diamond_value__gte', 0)), name='order_diamond_value_nonnegative'), models.CheckConstraint(condition=models.Q(('gold_amount__gte', 0)), name='order_gold_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('labour_amount__gte', 0)), name='order_labour_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('total_bill__gte', 0)), name='order_total_bill_nonnegative'), models.CheckConstraint(condition=models.Q(('dia_ct__gte', 0)), name='order_dia_ct_nonnegative'), models.CheckConstraint(condition=models.Q(('other_wt__gte', 0)), name='order_other_wt_nonnegative')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
