# Generated by Django 5.2.17 on 2026-09-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, upload_to='orders/thumbnails/'),
        ),
    ]
