# Generated by Django 5.2.17 on 2026-10-01 19:23

from django.db import migrations, models


def normalize_statuses(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(fulfilment_status__in=['New', 'In production', 'Ready']).update(fulfilment_status='')
    Order.objects.filter(fulfilment_status='Shipped').update(fulfilment_status='Delivered')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_sales_no_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_shipped_tracking',
        ),
        migrations.RunPython(normalize_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='fulfilment_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='', max_length=20),
        ),
    ]
