# Generated by Django 5.2.17 on 2026-10-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_order_shipped_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image2',
            field=models.ImageField(blank=True, upload_to='orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='thumbnail2',
            field=models.ImageField(blank=True, editable=False, upload_to='orders/thumbnails/'),
        ),
    ]
