# Generated by Django 5.2.17 on 2026-10-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_image2_order_thumbnail2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image2_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='thumbnail2_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='thumbnail_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
