# Generated by Django 5.2.17 on 2026-10-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_image2_data_order_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status_override',
            field=models.CharField(blank=True, choices=[('', 'Auto from payments'), ('Unpaid', 'Unpaid'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='', max_length=20),
        ),
    ]
