# Generated by Django 5.2.17 on 2026-10-01 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
        ('orders', '0007_order_payment_status_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_account_sales_unique',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('account', 'sales_no'), name='order_active_account_sales_unique'),
        ),
    ]
